commented steps

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -70,20 +70,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      -
-        name: Set up QEMU
+      - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
-      -
-        name: Set up Docker Buildx
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      -
-        name: Login to Docker Hub
+      - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Build and push
+      - name: Build and push
         uses: docker/build-push-action@v5
         with:
           push: true
@@ -103,37 +99,37 @@ jobs:
           location: australiaeast
           targetPort: 5000
       
-      - name: Get deployed DAST app url
-        run: |
-          export FQDN=$(az containerapp show -n devops-test-app -g devsecops-lab --query properties.configuration.ingress.fqdn -o tsv)
-          echo "TEST_APP_URL=https://$FQDN" >> $GITHUB_ENV
-          echo "TEST_APP_URL=https://$FQDN" 
-          curl https://$FQDN/ui
-          sed -i "s,http://localhost:5000,https://$FQDN,g" $GITHUB_WORKSPACE/openapi_specs/openapi3.yml
+      # - name: Get deployed DAST app url
+      #   run: |
+      #     export FQDN=$(az containerapp show -n devops-test-app -g devsecops-lab --query properties.configuration.ingress.fqdn -o tsv)
+      #     echo "TEST_APP_URL=https://$FQDN" >> $GITHUB_ENV
+      #     echo "TEST_APP_URL=https://$FQDN" 
+      #     curl https://$FQDN/ui
+      #     sed -i "s,http://localhost:5000,https://$FQDN,g" $GITHUB_WORKSPACE/openapi_specs/openapi3.yml
       
-      - name: ZAP Scan
-        uses: zaproxy/action-api-scan@v0.9.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          format: openapi
-          target: /zap/wrk/openapi_specs/openapi3.yml
-          rules_file_name: .zap/rules.tsv
-          cmd_options: '-a -c /zap/wrk/.zap/rules.tsv -T 1' # Increase timeout to 1 minute
-          fail_action: false
-          allow_issue_writing: false
+      # - name: ZAP Scan
+      #   uses: zaproxy/action-api-scan@v0.9.0
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
+      #     format: openapi
+      #     target: /zap/wrk/openapi_specs/openapi3.yml
+      #     rules_file_name: .zap/rules.tsv
+      #     cmd_options: '-a -c /zap/wrk/.zap/rules.tsv -T 1' # Increase timeout to 1 minute
+      #     fail_action: false
+      #     allow_issue_writing: false
 
-      - name: Upload ZAP report
-        id: artifact-zap
-        uses: actions/upload-artifact@v4
-        with:
-          name: zap-report
-          path: report_json.json
+      # - name: Upload ZAP report
+      #   id: artifact-zap
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: zap-report
+      #     path: report_json.json
         
-        # verify the application is accessible
-      - name: Verify Application Accessibility
-        run: |
-          curl -I https://devops-test-app.blacksmoke-339d2763.australiaeast.azurecontainerapps.io || exit 1
+      #   # verify the application is accessible
+      # - name: Verify Application Accessibility
+      #   run: |
+      #     curl -I https://devops-test-app.blacksmoke-339d2763.australiaeast.azurecontainerapps.io || exit 1
   
   image-scan:
     needs: [test]
